### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by tihoho** [Farfa7886/subwaySurfers-ezGUI#56]
Thanks bro! My son was very happy that we managed to add keys and balance to the game

**Comment by le0o0oo** [comment]
Glad it helped 😊

Check out also [Herr Erde's project](https://subway.herrerde.xyz) for a faster and easier experience in adding keys and balance

**Comment by tihoho** [comment]
> Glad it helped 😊
> 
> Check out also [Herr Erde's project](https://subway.herrerde.xyz) for a faster and easier experience in adding keys and balance

this is for 3rd version?

**Comment by le0o0oo** [comment]
i don't think it will make a difference the version since the game will convert it
